
path = r'd:\pomo\style.css'
with open(path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Line numbers are 1-based, so line 5908 is index 5907
# We want to keep everything up to line 5907
new_content = lines[:5907]

# Add the corrected section
new_content.append("@media (max-width: 768px) {\n")
new_content.append("  .pomo-info-title {\n")
new_content.append("    font-size: 2.2rem;\n")
new_content.append("  }\n")
new_content.append("\n")
new_content.append("  .pomo-info-btns {\n")
new_content.append("    flex-direction: column;\n")
new_content.append("    align-items: center;\n")
new_content.append("  }\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append("/* ===== POMO DETAILS & STEPS ===== */\n")
new_content.append(".pomo-details-section {\n")
new_content.append("  max-width: 800px;\n")
new_content.append("  margin: 0 auto 100px;\n")
new_content.append("  display: flex;\n")
new_content.append("  flex-direction: column;\n")
new_content.append("  gap: 60px;\n")
new_content.append("  padding: 0 20px;\n")
new_content.append("  animation: st-fade-in 1.2s ease-out;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-details-group {\n")
new_content.append("  text-align: center;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-details-title {\n")
new_content.append("  font-family: 'Outfit', sans-serif;\n")
new_content.append("  font-size: 2.2rem;\n")
new_content.append("  font-weight: 700;\n")
new_content.append("  color: #fff;\n")
new_content.append("  margin-bottom: 20px;\n")
new_content.append("  letter-spacing: -0.02em;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-details-text {\n")
new_content.append("  font-size: 1.05rem;\n")
new_content.append("  color: var(--text-secondary);\n")
new_content.append("  line-height: 1.8;\n")
new_content.append("  max-width: 700px;\n")
new_content.append("  margin: 0 auto;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-steps-grid {\n")
new_content.append("  display: grid;\n")
new_content.append("  grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));\n")
new_content.append("  gap: 20px;\n")
new_content.append("  margin-top: 20px;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card {\n")
new_content.append("  background: rgba(255, 255, 255, 0.03);\n")
new_content.append("  border: 1px solid rgba(255, 255, 255, 0.06);\n")
new_content.append("  border-radius: var(--radius-lg);\n")
new_content.append("  padding: 30px 20px;\n")
new_content.append("  text-align: center;\n")
new_content.append("  transition: all 0.4s cubic-bezier(0.16, 1, 0.3, 1);\n")
new_content.append("  position: relative;\n")
new_content.append("  overflow: hidden;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card:hover {\n")
new_content.append("  transform: translateY(-8px);\n")
new_content.append("  background: rgba(255, 255, 255, 0.05);\n")
new_content.append("  border-color: var(--accent-pink);\n")
new_content.append("  box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card::before {\n")
new_content.append("  content: '';\n")
new_content.append("  position: absolute;\n")
new_content.append("  top: 0;\n")
new_content.append("  left: 0;\n")
new_content.append("  width: 100%;\n")
new_content.append("  height: 2px;\n")
new_content.append("  background: linear-gradient(90deg, transparent, var(--accent-pink), transparent);\n")
new_content.append("  opacity: 0;\n")
new_content.append("  transition: opacity 0.4s;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card:hover::before {\n")
new_content.append("  opacity: 1;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-num {\n")
new_content.append("  width: 44px;\n")
new_content.append("  height: 44px;\n")
new_content.append("  border-radius: 50%;\n")
new_content.append("  background: rgba(59, 130, 246, 0.1);\n")
new_content.append("  border: 1px solid rgba(59, 130, 246, 0.2);\n")
new_content.append("  color: #60a5fa;\n")
new_content.append("  display: flex;\n")
new_content.append("  align-items: center;\n")
new_content.append("  justify-content: center;\n")
new_content.append("  font-size: 1.1rem;\n")
new_content.append("  font-weight: 800;\n")
new_content.append("  margin: 0 auto 20px;\n")
new_content.append("  transition: all 0.4s;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card:hover .pomo-step-num {\n")
new_content.append("  background: #2563eb;\n")
new_content.append("  color: #fff;\n")
new_content.append("  transform: scale(1.1);\n")
new_content.append("  box-shadow: 0 0 15px rgba(37, 99, 235, 0.4);\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card h4 {\n")
new_content.append("  font-size: 1.15rem;\n")
new_content.append("  color: #fff;\n")
new_content.append("  margin-bottom: 12px;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append(".pomo-step-card p {\n")
new_content.append("  font-size: 0.9rem;\n")
new_content.append("  color: var(--text-secondary);\n")
new_content.append("  line-height: 1.5;\n")
new_content.append("}\n")
new_content.append("\n")
new_content.append("@media (max-width: 600px) {\n")
new_content.append("  .pomo-steps-grid {\n")
new_content.append("    grid-template-columns: 1fr;\n")
new_content.append("  }\n")
new_content.append("}\n")

with open(path, 'w', encoding='utf-8') as f:
    f.writelines(new_content)
